unit DRSHELP;

interface

const

  hcAbout                = 62;
  hcAntivirs             = 49;
  hcAritmeticInstr       = 65;
  hcCDPlayer             = 32;
  hcChooseDrive          = 36;
  hcColor                = 54;
  hcCompareDirectories   = 38;
  hcConfigSystem         = 51;
  hcConfigurationMenu    = 9;
  hcConfirmation         = 57;
  hcCrypt                = 58;
  hcCzech                = 52;
  hcDiskCompare          = 31;
  hcDiskCopy             = 30;
  hcDiskEdit             = 24;
  hcDiskFormat           = 29;
  hcDiskInfo             = 28;
  hcDiskMap              = 25;
  hcDiskMenu             = 5;
  hcDiskName             = 26;
  hcDiskPark             = 27;
  hcDoors                = 1;
  hcDrivers              = 48;
  hcFileAttribs          = 20;
  hcFileCompare          = 17;
  hcFileConvert          = 22;
  hcFileCopy             = 11;
  hcFileCrypt            = 18;
  hcFileDateTime         = 21;
  hcFileDelete           = 14;
  hcFileEdit             = 65534;
  hcFileExit             = 23;
  hcFileGetSize          = 19;
  hcFileMenu             = 4;
  hcFileReceive          = 15;
  hcFileRename           = 12;
  hcFileSort             = 37;
  hcFileUndelete         = 16;
  hcFileView             = 10;
  hcInstructionFile      = 63;
  hcKeyboard             = 53;
  hcLeft                 = 2;
  hcLogout               = 34;
  hcMkdir                = 13;
  hcMouse                = 56;
  hcMovInstr             = 67;
  hcNetworkMenu          = 6;
  hcNoContext            = 0;
  hcPalette              = 55;
  hcPanelsMenu           = 7;
  hcProcesorFunction     = 69;
  hcProtectedInstr       = 70;
  hcRegisters            = 64;
  hcRight                = 3;
  hcRotInstr             = 66;
  hcRunInstr             = 68;
  hcSaveOption           = 61;
  hcScreenMode           = 60;
  hcSetScreenSaver       = 59;
  hcShowHidePanel        = 35;
  hcStringInstr          = 71;
  hcToolsASCII           = 41;
  hcToolsCalc            = 40;
  hcToolsCalendar        = 39;
  hcToolsDateTime        = 46;
  hcToolsDupli           = 44;
  hcToolsFindFile        = 43;
  hcToolsInfo            = 42;
  hcToolsMask            = 45;
  hcToolsMenu            = 8;
  hcTSRPrograms          = 47;
  hcUsedCommands         = 50;
  hcUserList             = 33;

implementation

end.
