unit DRSHELP;

interface

const

  hcAbout                = 61;
  hcAntivirs             = 48;
  hcAritmeticInstr       = 64;
  hcCDPlayer             = 31;
  hcChooseDrive          = 35;
  hcColor                = 53;
  hcCompareDirectories   = 37;
  hcConfigSystem         = 50;
  hcConfigurationMenu    = 9;
  hcConfirmation         = 56;
  hcCrypt                = 57;
  hcCzech                = 51;
  hcDiskCompare          = 30;
  hcDiskCopy             = 29;
  hcDiskEdit             = 23;
  hcDiskFormat           = 28;
  hcDiskInfo             = 27;
  hcDiskMap              = 24;
  hcDiskMenu             = 5;
  hcDiskName             = 25;
  hcDiskPark             = 26;
  hcDoors                = 1;
  hcDrivers              = 47;
  hcFileAttribs          = 20;
  hcFileCompare          = 16;
  hcFileConvert          = 21;
  hcFileCopy             = 10;
  hcFileCrypt            = 17;
  hcFileDelete           = 13;
  hcFileEdit             = 65534;
  hcFileExit             = 22;
  hcFileGetSize          = 18;
  hcFileInformation      = 19;
  hcFileMenu             = 4;
  hcFileReceive          = 14;
  hcFileRename           = 11;
  hcFileSort             = 36;
  hcFileUndelete         = 15;
  hcFileView             = 65532;
  hcInstr386             = 71;
  hcInstr486             = 72;
  hcInstructionFile      = 62;
  hcKeyboard             = 52;
  hcLeft                 = 2;
  hcLogout               = 33;
  hcMkdir                = 12;
  hcMouse                = 55;
  hcMovInstr             = 66;
  hcNecInstr             = 73;
  hcNetworkMenu          = 6;
  hcNoContext            = 0;
  hcOtherProcesors       = 74;
  hcPalette              = 54;
  hcPanelsMenu           = 7;
  hcProcesorFunction     = 68;
  hcProtectedInstr       = 69;
  hcRegisters            = 63;
  hcRight                = 3;
  hcRotInstr             = 65;
  hcRunInstr             = 67;
  hcSaveOption           = 60;
  hcScreenMode           = 59;
  hcSetScreenSaver       = 58;
  hcShowHidePanel        = 34;
  hcStringInstr          = 70;
  hcToolsASCII           = 40;
  hcToolsCalc            = 39;
  hcToolsCalendar        = 38;
  hcToolsDateTime        = 45;
  hcToolsDupli           = 43;
  hcToolsFindFile        = 42;
  hcToolsInfo            = 41;
  hcToolsMask            = 44;
  hcToolsMenu            = 8;
  hcTSRPrograms          = 46;
  hcUsedCommands         = 49;
  hcUserList             = 32;

implementation

end.
